travis:
  secure:
    BINSTAR_TOKEN: X+22qw9IScm9kkONqXOdblfppNYQWfEe6hbJIkjUtbxd3i6nrqXe0eSROK+4ZntFLLX5HSm4mxjeU2FkR51xdFPrgNznQDjudSX6tQEHkxX8IoqPbY/eAmJe0+IB073hiMcokvyiDc+LcMzNQ07xkwD6WlxcjQJsF5xPkeAreqmct6P8UIVU0U0DFkOAPB9oDAMBbqJlRRjfJKso/OpkqE3EOv0qiZPIumdLiYDpk2hPAtH4aum+X4fRWbXuV3y6jZ8hl9i9HvmSPopU5zGC6MSH3/gYophSsadcM0mM8lb5Qt75c5cp9A0lx177VyGBnqJf90GB5bN7ZnrwSzvRVVMqwBSxJFuPZXB3SV3pAdhdb//LF2resFRT55mvICCRH7QtRGSeazLKalcQ1mf6MQTdUgH3rtxeibwJhQZxXfnI015mOzWQMO2QIKxLs3JI9rYvZvi+EuBzoUl0IyQ5Dgl4M6CftzFZiK5EUK9Xm7dPub6i+xDspx4Fztc8R9rjWH+RCBpQ34ir/hLwS+A7EcJinFd8jLwvgcy92+1M3TSyi/WIaM/D2Q5ggnQ796FByWozSGqQZbqCDV/4SBRd0yIaoLI4+aOxM3fPt8SwAkXyvajxrW3qsg2A6eZkWD9VmvF8qrlLlXrYmfNb+iIFNnPIfNIX4RGDbiTPOTeVeko=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
