travis:
  secure:
    BINSTAR_TOKEN: SHkFv4OAxxt+8ZF6YKkuvn255ommtKk/zQB4Z32Ar4pVeivDryUYhSRwKLz6fBBezypa07fv0pdtd2jzjAj0oOtUIxsvnJr0jMqRsY7XMHtJTmIzXnp5gFEInOmZjUoHOSVyVmVtvAAwIa6TMR6vXbg6nBy2XxMs+EjYSl6MXHKUcJ0h+yYcrzVC9kJ6/napYKQCYAjBOIYBZsz1Q8gOFU16Jw9L8cjeheJvKTg/CF6fVA2Fs1X2GI86H2pzdi0V66MLpkm2KuMppJ8nsMhRr6sYWfmaUF4Jn/uQUazP6pUe7sWtf5Nu7bzHupe92gvKl7qvOneqH6PRI50iNfsMgEqgb/p3gWQ4hbbItST/1XaXbvDboi0g0Uqfo7mbW1QBrkFJjZRBvROBuCi5XNOoPda9MyDiYeXCiWpbcx16DHAcKwrxr5Grr+z9+WCMEWnCx7I7BXPCTcVlkghD+v9IyRdKxkSDZXHfp0fHVEKwx32sGq/qkpSfYRBUyJLrgf1iyg8qdZ7eERpTqXsEnwBmSrxdspeI61PK+taXZKidqKf+tfMkXq05SjHSFP39SLoK2xTQKTukqxMmO9mO+G8aJY8Ok6rho8VKMlraD6a+5G8xbPOauNWtNzSMZPvsQKmrXyVr/P4zgp+Ed0Z1rxb+y6s25jI7S8wQS14blTCozQg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
