travis:
  secure:
    BINSTAR_TOKEN: FikkGTRV7uan2CurZgSCBwZ1OxMy1fAWyyOxNYm/97i635g+QxzqZDBHUrsX3Jz9IpRTHI6aisYYldTdcJvHKp95IdhlkMU9Z4lgWjXL149Gysz/hmaLfyG3UShztCKvzIEd+cJOQocsG/z8SpVrXJ2AOYh+Mz1ROlStnYqMneC9tt+8ZnmmVpBkuH2RIla50arBqhKAFgnrUkMKGezLry8QlL2GK4Q2tULNF8kO0yWsxiJPfag9FTTfNctvdMzyUxKPiqMnZspvDjYdtWsJmr+93dLDgkAfukZqrPkKhi47OyT6ExH1NarEXr484utGbSjxun5Ny5vz01V1PIoprLXcKYKhBr46uSjtS8J1IFXt53DF9KTMQl8IXPpq0i7HU3XU4Zl+V9tHYmAmCSUkWzRWyC/Al/PRqt3fi1tcSwWs5ZQh5Z685HcEOf9blHoVDMJUA+yYErQcuyWRN3u638HHrhabotXnYydzxarHBu216AzTsgo3s2KljiyCkwxMI3FV72N+NtnPfec2tEr7V9QS0Ou5rwwNsQFhdEf+LPhwGA17FuZhMCGMSPzvGA1z0Bi6ADApxlsHK0/T0K9yI3sz74qZ9pvmB68s5qHSRCZQJkrFaYRYnpcRFs6KMBA7xDJeNEgQBsLpIdAOs9m2VV5qLcGGZv18FzJeA17wLmg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
